### ISSUE TITLE
ECONNREFUSED is not handle with starttls = true

### ISSUE THREAD

**Issue by ArthurG94** [shaozi/ldap-authentication#18]
Hello,
I think i found a bug with the **starttls** option:

When **starttls** is defined to **true** and the server is unreachable, no rejection is triggered.

The callback of **starttls** ldapjs's method is not called but trigger a **connectRefused** event who can be used.

If i disable **starttls** and use **ldaps://**, the rejection is triggered.

**Comment by shaozi** [comment]
I can take a look. Do you have a suggestion to fix it?

**Comment by ArthurG94** [comment]
Yes, i did a pull request #19

**Comment by shaozi** [comment]
Great job! Merged!
