### ISSUE TITLE
Allow to search for group membership where the user match is not the "dn" attribute on the user object

### ISSUE THREAD

**Issue by billneff79** [shaozi/ldap-authentication#22]
The `_searchUserGroups` method currently assumes that the attribute to match on the user object for group membership is `dn`:

https://github.com/shaozi/ldap-authentication/blob/d0f348e68d419bc3e0527933bd196303f8a57c56/index.js#L121

In our ldap, one of the ways we search for group membership is actually `uid`, so we need the ability to configure an alternative to the default of `dn` for matching.

**Comment by billneff79** [comment]
Thanks for merging @shaozi .  Can you do a release to npm with this in it?

**Comment by shaozi** [comment]
published

**Comment by billneff79** [comment]
Awesome!  I pulled it down and it's working well.  Thanks again @shaozi !
