### ISSUE TITLE
Feature Request: Allow Passing Requested Attribute List

### ISSUE THREAD

**Issue by mehmet6parmak** [shaozi/ldap-authentication#29]
Current implementation requests all attributes by default and does not allow requesting custom attribute lists. 
Default attribute list does not include calculated attributes and as far as I see there is no way to get calculated attributes currently.

If library allows passing custom requested attribute list, it will be possible to get calculated properties too.

**Comment by shaozi** [comment]
Sounds like a good suggestion. Do you have an example?

**Comment by mehmet6parmak** [comment]
You mean an example attribute name, right? In my case it was the "isMemberOf" attribute, which we use to get user group memberships. 
I am not an expert about ldap and don't know if this is because of a configuration of our server or something common.

**Comment by vfilatov** [comment]
> Sounds like a good suggestion. Do you have an example?

http://ldapjs.org/client.html#search
there are few options such as `scope`, `filter`, `attributes`, etc
`ldap-authentication` uses only first two.
Our company AD contains "zillions" of attributes and would be great if I could limit traffic only to ['mail', 'displayName', 'image']...
Other then that `ldap-authentication` is good project, I but have to stick to https://github.com/ldapjs/node-ldapjs until this issue resolved.
