### ISSUE TITLE
thumbnailPhoto

### ISSUE THREAD

**Issue by SoloEgo** [shaozi/ldap-authentication#36]
Hi, i`ve tried to get user thumbnailPhoto, but in response i get "����\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00��\...", it`s a bit weird... How i can get base64 string or somthig like this?

**Comment by shaozi** [comment]
It probably is a binary string. you can try `btoa(s)`

**Comment by fabiang** [comment]
`thumbnailPhoto` is binary, so a simple base64encode() should be enough. Note that those thumbnails are usually stored as JPEG (image/jpeg), but I would recommend using an MIME library to get the correct MIME type for the binary string.

**Comment by SoloEgo** [comment]
Yep, added check attribute in function in index.js and it work properly, many thanks
