### ISSUE TITLE
usernameAttribute multiple values

### ISSUE THREAD

**Issue by myurzep** [shaozi/ldap-authentication#47]
Hello! :wave:
Is it possible to specify multiple values in the `usernameAttribute` to authorize the user either by name or by email? For example, `|(sAMAccountName={{username}})(mail={{username}})` does not work.
Maybe this is planned in the future?
Thank you! :blush:

**Comment by shaozi** [comment]
LDAP authentication has to use the username dn and password to bind.

**Comment by myurzep** [comment]
Thanks for the answer!
