### ISSUE TITLE
Search for groups is broken since ldapjs 3.0.0

### ISSUE THREAD

**Issue by pizzafroide** [shaozi/ldap-authentication#56]
Since [ldapjs 3.0.0](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0), message objects no longer have a `.object` accessor. It is replaced by `.pojo`.

> Message objects no longer have a `.object` accessor. This has been replaced with the `.pojo` accessor. It didn't make any sense to have a message object with an accessor that returns an object (it's confusing). The `.pojo` accessor states what will be returned: a plain JavaScript object. You may find that the actual message object now has fields you can directly use. See [#841](https://github.com/ldapjs/node-ldapjs/issues/841).

But ldap-authentication still uses the old accessor [here](https://github.com/shaozi/ldap-authentication/blob/866bcd5d4d1eb8d16cc3d4b2bfc641b970ea9dc9/index.js#L151) and the `groups` property in the resulting object is therefore an array of `undefined`...

**Comment by mmende** [comment]
I made a PR to fix this issue: https://github.com/shaozi/ldap-authentication/pull/57

**Comment by MalfuncEddie** [comment]
not sure howe this works but the latest version on npm does not contain this fix?

https://www.npmjs.com/package/ldap-authentication/v/3.0.3?activeTab=code

**Comment by pizzafroide** [comment]
#57 is merged but the fix won't be available on npm until the next release. Dunno when it's planned though.
